[package]
name = "vmr"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
clap = { version = "4.5.54", features = ["derive"] }
env_logger = "0.11.8"
flagset = "0.4.7"
log = "0.4.29"
num-derive = "0.4.2"
num-traits = "0.2.19"
strum = { version = "0.27.0", features = ["derive"] }

[lib]
name = "libvmr"
path = "src/lib.rs"
crate-type = ["lib"]


[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
indexing_slicing = "warn"
unreachable = "warn"
unimplemented = "warn"
todo = "warn"
string_slice = "warn"
panic_in_result_fn = "warn"
panic = "warn"
exit = "warn"
get_unwrap = "warn"
unwrap_in_result = "warn"
let_underscore_future = "warn"
let_underscore_must_use = "warn"
unused_result_ok = "warn"
map_err_ignore = "warn"
assertions_on_result_states = "warn"
mem_forget = "warn"
undocumented_unsafe_blocks = "warn"
multiple_unsafe_ops_per_block = "warn"
unnecessary_safety_doc = "warn"
unnecessary_safety_comment = "warn"
float_cmp = "warn"
float_cmp_const = "warn"
lossy_float_literal = "warn"
cast_sign_loss = "warn"
invalid_upcast_comparisons = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_possible_truncation = "warn"
rc_mutex = "warn"
debug_assert_with_mut_call = "warn"
iter_not_returning_iterator = "warn"
expl_impl_clone_on_copy = "warn"
infallible_try_from = "warn"
dbg_macro = "warn"
allow_attributes_without_reason = "warn"
